[programs.localnet]
solana_counter = "HUgqzu2CDqrCPxmbAzzo9YqPVw9hECyEzaMCgtttmjSL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cloudyun/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
